version: '3'
services:
  angular_app:
    image: investinyangular
    ports:
      - "4200:4200"
  springboot_app:
    image: investinybackend
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: investiny
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
